<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Session extends \AppBundle\Entity\Session implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'formules', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'disciplines', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'titreSession', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'dateSession', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'nbPlace', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'inscriptionCollection', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'descriptionSession', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'prix', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'orderNumber'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'formules', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'disciplines', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'titreSession', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'dateSession', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'nbPlace', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'inscriptionCollection', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'descriptionSession', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'prix', '' . "\0" . 'AppBundle\\Entity\\Session' . "\0" . 'orderNumber'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Session $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormules($formules)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormules', [$formules]);

        return parent::setFormules($formules);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormules', []);

        return parent::getFormules();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisciplines($disciplines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisciplines', [$disciplines]);

        return parent::setDisciplines($disciplines);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisciplines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisciplines', []);

        return parent::getDisciplines();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreSession($titreSession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreSession', [$titreSession]);

        return parent::setTitreSession($titreSession);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreSession', []);

        return parent::getTitreSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSession($dateSession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSession', [$dateSession]);

        return parent::setDateSession($dateSession);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSession', []);

        return parent::getDateSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPlace($nbPlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPlace', [$nbPlace]);

        return parent::setNbPlace($nbPlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPlace', []);

        return parent::getNbPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscriptionCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscriptionCollection', []);

        return parent::setInscriptionCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptionCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptionCollection', []);

        return parent::getInscriptionCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\AppBundle\Entity\Inscription $inscriptionCollection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', [$inscriptionCollection]);

        return parent::addInscription($inscriptionCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\AppBundle\Entity\Inscription $inscriptionCollection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', [$inscriptionCollection]);

        return parent::removeInscription($inscriptionCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionSession($descriptionSession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionSession', [$descriptionSession]);

        return parent::setDescriptionSession($descriptionSession);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionSession', []);

        return parent::getDescriptionSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderNumber($orderNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderNumber', [$orderNumber]);

        return parent::setOrderNumber($orderNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderNumber', []);

        return parent::getOrderNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
