<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjc9e8e\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjc9e8e/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZjc9e8e.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZjc9e8e\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZjc9e8e\appDevDebugProjectContainer([
    'container.build_hash' => 'Zjc9e8e',
    'container.build_id' => '0475fa4a',
    'container.build_time' => 1559744409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZjc9e8e');
