<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRj4khnr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRj4khnr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRj4khnr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRj4khnr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRj4khnr\appDevDebugProjectContainer([
    'container.build_hash' => 'Rj4khnr',
    'container.build_id' => '1ee8fa28',
    'container.build_time' => 1588179435,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRj4khnr');
